apiVersion: v2
name: alloy
description: 'Grafana Alloy'
type: application
version: 0.12.5
appVersion: 'v1.7.5'
icon: https://raw.githubusercontent.com/grafana/alloy/main/docs/sources/assets/alloy_icon_orange.svg

dependencies:
  - name: crds
    version: "0.0.0"
    condition: crds.create
