name: alloy-example

include:
  - ./grafana.yaml
  - ./databases.yaml

services:
  alloy:
    image: grafana/alloy:latest@sha256:8abcd0d97a97099cabb34be8dcfc448fca6c35931ae9291aaf74056105dedcca
    pull_policy: always
    profiles: ["alloy"]
    restart: on-failure
    volumes:
      - ./config/alloy:/etc/alloy
    environment:
      REMOTE_WRITE_HOST: mimir:9009
      LOKI_HOST: loki:3100
      TEMPO_HOST: tempo:4317
      PYROSCOPE_HOST: pyroscope:4040
    depends_on:
      - mimir
      - loki
      - tempo
      - pyroscope
    command:
      - run
      - /etc/alloy/config.alloy
      - --storage.path=/var/lib/alloy/data
      - --server.http.listen-addr=0.0.0.0:12345
      - --stability.level=experimental # Enable all functionality
    ports:
      - "12345:12345"
