extraObjects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: grafana-cloud
  stringData:
    PROMETHEUS_HOST: 'https://prometheus-us-central1.grafana.net/api/prom/push'
    PROMETHEUS_USERNAME: '123456'
