{{- $values := (mustMergeOverwrite .Values.alloy (or .Values.agent dict)) -}}
{{- if $values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alloy.secret.name" . }}
  namespace: {{ include "alloy.namespace" . }}
  labels:
    {{- include "alloy.labels" . | nindent 4 }}
    app.kubernetes.io/component: config
type: Opaque
stringData:
  {{- if $values.secret.content }}
  {{ include "alloy.secret.key" . }}: |- {{- (tpl  $values.secret.content .) | nindent 4 }}
  {{- else }}
  {{ include "alloy.secret.key" . }}: |- {{- .Files.Get "config/example.alloy" | trim | nindent 4 }}
  {{- end }}
{{- end }}
