name: alloy-integration-tests
services:
  mimir:
    image: grafana/mimir:3.0.0
    volumes:
      - ./configs/mimir:/etc/mimir-config
    entrypoint:
      - /bin/mimir
      - -config.file=/etc/mimir-config/mimir.yaml
    ports:
      - "9009:9009"
    networks:
      - integration-tests

  tempo:
    image: grafana/tempo:2.6.1
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./configs/tempo/tempo.yaml:/etc/tempo.yaml
    ports:
      - "14268:14268"  # jaeger ingest
      - "3200:3200"    # tempo
      - "9095:9095"    # tempo grpc
      - "4319:4317"    # otlp grpc
      - "4320:4318"    # otlp http
      - "9411:9411"    # zipkin
    networks:
      - integration-tests

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 10
      KAFKA_NUM_PARTITIONS: 3
    healthcheck:
      test: [ "CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 || exit 1" ]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - integration-tests

  kafka-gen:
    depends_on:
      - kafka
    build:
      dockerfile: ./integration-tests/docker/configs/kafka/Dockerfile
      context: ../../
    networks:
      - integration-tests

  loki:
    image: grafana/loki:3.5.8
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    healthcheck:
      test: wget -q -O - http://localhost:3100/services | grep -v Running || true
      interval: 1s
      timeout: 5s
      retries: 60
    networks:
      - integration-tests

  otel-gen:
    build:
      dockerfile: ./integration-tests/docker/configs/otel-gen/Dockerfile
      context: ../../
    environment:
      - OTEL_EXPORTER_ENDPOINT=${OTEL_EXPORTER_ENDPOINT:-alloy-otlp-metrics:4318}
    networks:
      - integration-tests
    ports:
      - "8443:8443"

  prom-gen:
    build:
      dockerfile: ./integration-tests/docker/configs/prom-gen/Dockerfile
      context: ../../
    ports:
      - "9001:9001"
    networks:
      - integration-tests

  redis:
    image: redis:6.0.9-alpine
    ports:
      - "6379:6379"
    networks:
      - integration-tests

  redis-init:
    image: redis:6.0.9-alpine
    depends_on:
      - redis
    volumes:
      - ./tests/redis/init_redis.sh:/init_redis.sh
    command: sh /init_redis.sh
    restart: "no"
    networks:
      - integration-tests

  snmp-simulator:
    image: tandrup/snmpsim:v0.4
    container_name: snmpsim
    ports:
      - "161:161/udp"
    networks:
      - integration-tests

networks:
  integration-tests:
    driver: bridge
