image:
  repository: piotrgrafana/alloy-otelcol-alias
  tag: latest

command: 
  name: "bin/otelcol"

mode: deployment

config:
  receivers:
    # Disable unsupported/default receivers from chart defaults.
    prometheus: null
  service:
    pipelines:
      metrics:
        receivers: [otlp]
