{{- if .Values.gateway.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "alloy.fullname" . }}-gateway
  namespace: {{ include "alloy.namespace" . }}
  labels:
    {{- include "alloy.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
    {{- with .Values.gateway.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.gateway.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.gateway.service.type }}
  {{- if .Values.gateway.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.gateway.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.gateway.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml .Values.gateway.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  selector:
    {{- include "alloy.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
  ports:
  - name: http
    port: {{ .Values.gateway.port }}
    targetPort: http
    protocol: TCP
    {{- if and (eq .Values.gateway.service.type "NodePort") .Values.gateway.service.nodePort }}
    nodePort: {{ .Values.gateway.service.nodePort }}
    {{- end }}
  {{- if .Values.gateway.tls.enabled }}
  - name: https
    port: {{ .Values.gateway.tls.port }}
    targetPort: https
    protocol: TCP
  {{- end }}
  {{- if .Values.gateway.serviceMonitor.enabled }}
  - name: metrics
    port: 9113
    targetPort: metrics
    protocol: TCP
  {{- end }}
{{- end }}
