name: 'Apply labels on a new issue'
on:
  issues:
    types: [opened]

permissions: read-all

jobs:
  apply-labels-on-issue:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'grafana' }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
    
      - name: Run apply-component-labels.sh
        run: ./.github/workflows/scripts/apply-component-labels.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.number }}
          BODY: ${{ github.event.issue.body }}
