name: Check Linux build image

on:
  pull_request:
    paths:
      - 'tools/build-image/*'
      - '.github/workflows/check-linux-build-image.yml'

jobs:
  check-linux-build-image:
    strategy:
      matrix:
        build:
          - runtime: golang:1.24.1-alpine3.21
          - runtime: mcr.microsoft.com/oss/go/microsoft/golang:1.24.1-bookworm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Remove unnecessary files
        run: |
            rm -rf /usr/share/dotnet
            rm -rf "$AGENT_TOOLSDIRECTORY"
            rm -rf /opt/ghc
            rm -rf "/usr/local/share/boost"
            rm -rf /opt/hostedtoolcache

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Create test Linux build image
        uses: docker/build-push-action@v6.15.0
        with:
          platforms: linux/amd64,linux/arm64
          context: ./tools/build-image
          push: false
          tags: grafana/alloy-build-image:latest
          build-args: |
            GO_RUNTIME=${{ matrix.build.runtime }}
