name: Check Linux build image

on:
  pull_request:
    paths:
      - 'tools/build-image/*'
      - '.github/workflows/check-linux-build-image.yml'

permissions:
  contents: read

jobs:
  check-linux-build-image:
    strategy:
      matrix:
        build:
          - runtime: golang:1.25.1-alpine3.22
          - runtime: mcr.microsoft.com/oss/go/microsoft/golang:1.25.1-bookworm
    runs-on: ubuntu-latest-8-cores
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          persist-credentials: false

      - name: Remove unnecessary files
        run: |
            rm -rf /usr/share/dotnet
            rm -rf "$AGENT_TOOLSDIRECTORY"
            rm -rf /opt/ghc
            rm -rf "/usr/local/share/boost"
            rm -rf /opt/hostedtoolcache

      - name: Setup QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Create test Linux build image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          platforms: linux/amd64,linux/arm64
          context: ./tools/build-image
          push: false
          tags: grafana/alloy-build-image:latest
          build-args: |
            GO_RUNTIME=${{ matrix.build.runtime }}
