name: Check Linux build image

on:
  pull_request:
    paths:
      - 'tools/build-image/*'
      - '.github/workflows/check-linux-build-image.yml'

permissions:
  contents: read

jobs:
  check-linux-build-image:
    strategy:
      matrix:
        build:
          - runtime: golang:1.25.7-alpine3.23
          - runtime: mcr.microsoft.com/oss/go/microsoft/golang:1.25.7-bookworm
    runs-on: ubuntu-latest-8-cores
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Remove unnecessary files
        run: |
            rm -rf /usr/share/dotnet
            rm -rf "$AGENT_TOOLSDIRECTORY"
            rm -rf /opt/ghc
            rm -rf "/usr/local/share/boost"
            rm -rf /opt/hostedtoolcache

      - name: Setup QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

      - name: Create test Linux build image
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6.19.2
        with:
          platforms: linux/amd64,linux/arm64
          context: ./tools/build-image
          push: false
          tags: grafana/alloy-build-image:latest
          build-args: |
            GO_RUNTIME=${{ matrix.build.runtime }}
