name: Check github issue templates
on: pull_request

permissions:
  contents: read

jobs:
  regenerate-gh-issue-templates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Regenerate github issue templates
        run: |
          make generate-gh-issue-templates
          if ! git diff --exit-code; then
            echo "GitHub issue templates are not up to date. Please run 'make generate-gh-issue-templates' and commit changes!" >&2
            exit 1
          fi