name: 'Generate component labels'
permissions:
  contents: read
on:
  push:
    branches: [main]
    paths:
      - ./.github/workflows/generate-component-labels.yml
      - ./.github/workflows/scripts/generate-component-labels.sh
      # TODO - be more precise and only run if a new component readme file is created, this will also run on modifications
      - './docs/sources/reference/components/**/*.md'
      - '!./docs/sources/reference/components/**/_index.md'
  workflow_dispatch:

jobs:
  generate-component-labels:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'grafana' }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Generate component labels
        run: ./.github/workflows/scripts/generate-component-labels.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
