name: 'Generate component labels'
on:
  push:
    branches: [main]
    paths:
      - ./.github/workflows/generate-component-labels.yml
      - ./.github/workflows/scripts/generate-component-labels.sh
      # TODO - be more precise and only run if a new component readme file is created, this will also run on modifications
      - './docs/sources/reference/components/**/*.md'
      - '!./docs/sources/reference/components/**/_index.md'
    workflow_dispatch:

jobs:
  generate-component-labels:
    runs-on: ubuntu-24.04
    if: ${{ github.repository_owner == 'grafana' }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Generate component labels
        run: ./.github/workflows/scripts/generate-component-labels.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

