name: Test Helm chart
on: pull_request

permissions:
  contents: read

jobs:
  regenerate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Regenerate docs
        run: |
          docker run --rm \
            -v "$(pwd)/operations/helm/charts/alloy:/helm-docs" \
            -u "$(id -u)" \
            jnorwood/helm-docs
          if ! git diff --exit-code; then
            echo "Helm chart documentation is not up to date. Please run 'make generate-helm-docs' and commit changes!" >&2
            exit 1
          fi

  regenerate-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Install Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1
        with:
          # renovate: datasource=github-releases packageName=helm/helm
          version: v3.10.3

      - name: Regenerate tests
        run: |
          make generate-helm-tests
          if [ ! -z "$(git status --porcelain)" ]; then
            echo "Helm chart tests are not up to date. Please run 'make generate-helm-tests' and commit changes!" >&2
            exit 1
          fi

  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1
        with:
          # renovate: datasource=github-releases packageName=helm/helm
          version: v3.10.3

      - name: Install Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.13.3'
          check-latest: true

      - name: Install chart-testing
        uses: helm/chart-testing-action@6ec842c01de15ebb84c8627d2744a0c2f2755c9f # v2.8.0

      - name: Determine changed charts
        id: list-changed
        run: |
          changed=$(ct list-changed --config ./operations/helm/ct.yaml)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Lint charts
        run: ct lint --config ./operations/helm/ct.yaml

      - name: Create kind cluster
        uses: helm/kind-action@92086f6be054225fa813e0a4b13787fc9088faab # v1.13.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Add dependency chart repos
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

      - name: Install Prometheus Operator CRDs
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          helm install my-prometheus-operator-crds prometheus-community/prometheus-operator-crds --version 6.0.0

      - name: Test charts
        run: ct install --config ./operations/helm/ct.yaml
