name: Lint
on:
  workflow_call:
    inputs:
      go-version:
        required: true
        type: string
        description: "Go version to use"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code ğŸ›ï¸
      uses: actions/checkout@v4

    - name: Set up Go ğŸ—ï¸
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}
        cache: false

    - name: Lint Go (main module) ğŸ”
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.64.7

    - name: Lint Go (syntax module) ğŸ”
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.64.7
        working-directory: ./syntax/

    - name: Lint Alloy ğŸ”
      run: make run-alloylint

    - name: Shellcheck ğŸ”
      uses: azohra/shell-linter@latest
      with:
        path: "\
          packaging,\
          production,\
          tools/ci,\
          tools/release,\
          docs/sources/tutorials/assets\
          "
