name: Lint
on:
  workflow_call:

permissions:
  contents: read

jobs:
  lint_go:
    name: Lint Go
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        persist-credentials: false

    - name: Set up Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        go-version-file: go.mod
        cache: false

    - name: Lint alloy module
      uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
      with:
        # renovate: datasource=github-releases packageName=golangci/golangci-lint
        version: v2.4.0

    - name: Lint syntax module
      uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
      with:
        # renovate: datasource=github-releases packageName=golangci/golangci-lint
        version: v2.4.0
        working-directory: ./syntax/

    - name: Run custom linters
      run: make run-alloylint

  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        persist-credentials: false

    - name: Shellcheck
      uses: Azbagheri/shell-linter@30a9cf3f6cf25c08fc98f10d7dc4167f7b5c0c00 # v0.8.0
      with:
        path: "\
          packaging,\
          production,\
          tools/ci,\
          tools/release,\
          docs/sources/tutorials/assets\
          "

  lint_ui:
    name: Lint UI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: internal/web/ui

    steps:
    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        persist-credentials: false

    - name: Set up Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version-file: internal/web/ui/.nvmrc

    - name: Install dependencies
      run: npm install

    - name: Lint
      run: npm run lint

    - name: Format
      run: npm run format
