name: Lint
on:
  workflow_call:

jobs:
  lint_go:
    name: Lint Go
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code ğŸ›ï¸
      uses: actions/checkout@v4

    - name: Set up Go ğŸ—ï¸
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
        cache: false

    - name: Lint alloy module ğŸ”
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.64.7

    - name: Lint syntax module ğŸ”
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.64.7
        working-directory: ./syntax/

    - name: Run custom linters ğŸ”
      run: make run-alloylint

  shellcheck:
    name: Shellcheck ğŸ”
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code ğŸ›ï¸
      uses: actions/checkout@v4

    - name: Shellcheck ğŸ”
      uses: azohra/shell-linter@latest
      with:
        path: "\
          packaging,\
          production,\
          tools/ci,\
          tools/release,\
          docs/sources/tutorials/assets\
          "

  lint_ui:
    name: Lint UI ğŸ”
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: internal/web/ui

    steps:
    - name: Checkout code ğŸ›ï¸
      uses: actions/checkout@v4

    - name: Set up Node.js ğŸ—ï¸
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install dependencies ğŸ“¦
      run: yarn

    - name: Lint ğŸ”
      run: yarn run lint:ci
