name: Test Linux system packages
on:
  push:
    branches:
      - main
    paths:
    - packaging/**
    - internal/tools/packaging_test/**
    - Makefile
    - tools/make/*.mk

permissions:
  contents: read

jobs:
  test_linux_system_packages:
    name: Test Linux system packages
    runs-on: ubuntu-latest
    container:
      image: grafana/alloy-build-image:v0.1.26@sha256:54ef2371fc6b049d932c58d4622c88b573b45c393b7622fe6cca492ac4525dbe
      volumes:
        - /var/run/docker.sock
    steps:
    - name: Checkout code
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        persist-credentials: false
    - name: Set ownership
      # https://github.com/actions/runner/issues/2033#issuecomment-1204205989
      run: |
          # this is to fix GIT not liking owner of the checkout dir
          chown -R $(id -u):$(id -g) $PWD
    - name: Set up Go
      uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
      with:
        go-version-file: go.mod
        # TODO: Enable caching later
        cache: false
    - run: DOCKER_OPTS="" make dist/alloy-linux-amd64
    - run: DOCKER_OPTS="" make test-packages
