name: Test Pyroscope PR
on:
  pull_request:

permissions:
  contents: read

jobs:
  test_pyroscope:
    name: Test pyroscope packages on Linux
    runs-on: ubuntu-latest
    if: >
      github.actor == 'korniltsev-grafanista' ||
      github.actor == 'simonswine' ||
      github.actor == 'aleks-p' ||
      github.actor == 'marcsanmi'
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version-file: go.mod
          cache: false

      - run: sudo make test-pyroscope
